<?PHP
/*
#PATHS
ROOT,/home/sample/public_html
ADMIN,/home/sample/public_html/admin
DATA_FILES_DIR,/home/system/cms/data/sample
LOCALE_FILES_DIR,/home/system/cms/locale
XSL_THEMES_DIR,/home/system/cms
SYSTEM_CONFIG_DIR,/home/system/cms/config/sample
MODULE_DIR,/home/system/cms/modules
TMP,/home/system/cms/transform
TMP_UPLOAD_DIR,/home/sample/public_html/uploads
#END
*/
?>